<html>
	<head>
		<meta charset="utf-8" />
		<title>App lista de contato</title>
		<!-- Css -->
		<link rel="stylesheet" type="text/css" href="/assets/styles/css/index.css">

		<!-- Fontawesome CDN-->
		<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.15.3/css/all.css" integrity="sha384-SZXxX4whJ79/gErwcOYf+zWLeJdY/qpuqC4cAa9rOGUstPomtqpuNWT9wdPEn2fk" crossorigin="anonymous">

		<!-- Fonts -->
		<link rel="preconnect" href="https://fonts.gstatic.com">
		<link href="https://fonts.googleapis.com/css2?family=Roboto:wght@400;500&display=swap" rel="stylesheet">
		<link href="https://fonts.googleapis.com/css2?family=Lato:wght@400;700&display=swap" rel="stylesheet">
	</head>

	<body>
		<?= $this->content() ?>
	</body>

<script src="/assets/js/index.js"></script>
</html>